version: "3"
services:
  game-jdbc:
    image: game-jdbc
    ports:
      - "8087:8080"
    networks:
      - game-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - game-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=game

networks:
  bank-mysql: